fix jest reporter error

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -17,13 +17,7 @@ jobs:
         uses: actions/setup-python@v5
         with:
           python-version: "3.10"
-      - name: Test Report
-        uses: dorny/test-reporter@v1
-        if: success() || failure()    # run this step even if previous step failed
-        with:
-          name: JEST Tests            # Name of the check run which will be created
-          path: reports.xml    # Path to test results
-          reporter: jest-junit        # Format of test results
+      
       - name: Install dependencies
         run: |
           python --version
@@ -31,6 +25,13 @@ jobs:
           pytest --version
       - name: run test
         run: pytest --junit-xml=reports.xml .
+      - name: Test Report
+        uses: dorny/test-reporter@v1
+        if: success() || failure()    # run this step even if previous step failed
+        with:
+          name: JEST Tests            # Name of the check run which will be created
+          path: reports.xml    # Path to test results
+          reporter: jest-junit        # Format of test results
   build:
     needs: [testing]
     runs-on: ubuntu-22.04
